### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by robsonbittencourt**
Update
jenkins to 0.18.0
mocha to 3.0.2

### CODE REVIEW

**Comment by robsonbittencourt** [comment]
@robsonrosa please make the code review.

**Comment by robsonrosa** [comment]
Well, as I said in "separated-gears" threas, update jenkins dependency is a quite unuseful, becaus this dependency will be obsolete when merging these branches. I am a little bit confusing about these latest branching and splitting projects. I'm not feel confident to merge these branches yet, sou I strongly recomment you do that, please.

**Comment by robsonbittencourt** [comment]
No problem @robsonrosa. Updating jenkins really was not necessary. But I tried to work on this pull request, as if unsure of the other branch.

**Comment by robsonrosa** [comment]
Yeah. You've got a point. The branches are hideen for each other. So, no problem with jenkins dependency here.

**Pull request merged**
